### ISSUE TITLE
can't import private key

### ISSUE THREAD

**Issue by gl4d** [BTCPrivate/archived-full-node-wallet#8]
Hey,
I'm getting this error when i'm trying to import my zclassic private key:

> ` java.lang.NullPointerExeption: null please ensure that btcpd is running and the key is in the correct form.`

btcpd is running and i'm sure that the key is correct, any ways to fix this?
regards,

**Comment by ch4ot1c** [comment]
Make sure you have the latest release, and make sure btcpd is indeed running! Are you running from the .jar?

**Comment by bearcreekrganics** [comment]
Same problem here. My first private key is resulting n an error. My second zcl private key was accepted but then the seep resulted in an error

**Comment by Pega88** [comment]
did this happen if you clicked 'OK' to sweep? It could be that the private key has no balance, or that the chain is not 100% synced up so no balance is yet visible. Then a sweep indeed fails, although the import should've worked. might be related to #28

**Comment by bearcreekrganics** [comment]
I'm thinking that I wasn't 100% synced up yet. But it's taking forever. I am currently downloading the blockchain to help it sync. faster. Instructions say to put the file in the same location as the btcp wallett. I'm not sure what this means, however. Stand by.

**Comment by bearcreekrganics** [comment]
Just as a time stamp. I'm finally on 99.6% sync. Still not working. Private keys will not import or sweep properly. Not sure why it is stuck on 99%. This is very frustrating.

**Comment by pogoetic** [comment]
I was also stuck on 99.6% for some time - I let it run overnight and it did end up syncing - however I am also having the sweep issue - PK import works but sweep fails (I am 100% synced and btcpd is running). Here is the full error msg: 

![btcp pk sweep error](https://user-images.githubusercontent.com/1137067/36992443-ee4faf44-2078-11e8-9aef-f67e586e5656.png)

**Comment by pogoetic** [comment]
This was mentioned in another thread but I think the error occurs when the address associated with the imported private key has a zero balance. When I exported my private keys from the Electrum wallet the list was 30 deep. I am importing and sweeping one by one and finding that the sweeps are working bit by bit, some fail, but overall my BTCP balance is inching up towards the value I would expect given my ZEC balance at the fork block height. @gl4d make sure you are trying all of your private keys one by one and importing/sweeping. My guess is the error is due to zero balances, and there seem to be lots of private keys depending on how many IN/OUT transactions occurred in your Electrum wallet.
